name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo "Hello World! Github Actions 🚀"